### PR TITLE
incubating supernova 

### PR DESCRIPTION
**Pull request by hero78119**
Per discussion offline, submit the initial PR to kick off the integration

background: https://github.com/microsoft/Nova/pull/204#issuecomment-1681182446
PR in Nova: https://github.com/microsoft/Nova/pull/204

### CODE REVIEW

**Comment by porcuquine** [comment]
@hero78119, I was going to open a PR to your PR, but I can't because of cross-repo permission issues, etc.

I made a few stylistic changes (just naming) and removed the `supernova` feature, since we are going to bring this in unconditionally. If this looks okay, maybe you can just merge to your branch.

See the last four commits.

https://github.com/lurk-lab/arecibo/compare/supernova-tweaks?expand=1

I and @huitseeker may have a few more changes we would ideally like to see before landing the first version here, and a few more of our team may also offer review comments. We'd like to get through all that quickly, though, and merge so we can iterate on additions in individual PRs here.

**Comment by porcuquine** [comment]
Actually, for the sake of maximum simplicity, and since we're trying to move somewhat quickly, I'll just go ahead and merge this as-is, bypassing the whole issue.

**Review by porcuquine — APPROVED** [review]
This is approved for the sake of merging, with the qualification that we intend to continue review here — as well as commit to incorporating any correctness fixes introduced to the original Nova PR merge.

**Comment by hero78119** [comment]
> @hero78119, I was going to open a PR to your PR, but I can't because of cross-repo permission issues, etc.
> 
> I made a few stylistic changes (just naming) and removed the `supernova` feature, since we are going to bring this in unconditionally. If this looks okay, maybe you can just merge to your branch.
> 
> See the last four commits.
> 
> https://github.com/lurk-lab/arecibo/compare/supernova-tweaks?expand=1
> 
> I and @huitseeker may have a few more changes we would ideally like to see before landing the first version here, and a few more of our team may also offer review comments. We'd like to get through all that quickly, though, and merge so we can iterate on additions in individual PRs here.

Cool, I just reviewed the change and LGTM! 
It's merged so I think new PR is unlock :)

**Pull request merged**
