### PR TITLE
chore: switch benches to hzkg/bn254

### LINKED ISSUE #278: CI: fix default GPU benchmark to run
We currently run an instance of an NIVC benchmark by default on merge, but that still runs on the pasta cycle.
We should shift that to BN256/Grumpkin, ideally on KZG.

### PR DESCRIPTION
**Pull request by huitseeker**
Fixes #278

### CODE REVIEW

**Comment by huitseeker** [comment]
!gpu-benchmark

**Review by adr1anh — APPROVED** [review]

**Comment by huitseeker** [comment]
Note to self: investigating #281

**Review by storojs72 — APPROVED** [review]

**Comment by samuelburnham** [comment]
!benchmark --features cuda,asm

**Comment by huitseeker** [comment]
Now that I have [the data for a branch that does not have any calls to the MSM in the IPA](https://github.com/lurk-lab/arecibo/issues/281#issuecomment-1936377761) (which shows no change), I'm comfortable merging this.

**Review by mpenciak — APPROVED** [review]

**Review by storojs72 — APPROVED** [review]

**Review by adr1anh — APPROVED** [review]

**Review by mpenciak — APPROVED** [review]

**Pull request merged**
