### PR TITLE
IPA Solidity unit-test generator

### PR DESCRIPTION
**Pull request by storojs72**
This PR is a first step to solve verifier's Rust <-> Solidity compatibility problem (https://github.com/lurk-lab/arecibo/issues/337)

With a help of [Handlebars](https://github.com/sunng87/handlebars-rust) templating engine this PR adds IPA unit-test which dynamically generates exact [ipa.t.sol](https://github.com/lurk-lab/solidity-verifier/blob/main/test/ipa.t.sol) from our Solidity verifier (checked manually by running forge tests in Solidity with Solidity file generated by Rust).

**How to run?**

In order to create ipa.t.sol directly from Rust (Arecibo) environment I used following commands:

```
cargo test test_solidity_compatibility_ipa --release -- --ignored --nocapture > ipa.t.sol
cat ipa.t.sol | sed '1,3d' | sed -n -e :a -e '1,4!{P;N;D;};N;ba' > tmp.file && mv tmp.file ipa.t.sol
```

The ignored test `test_solidity_compatibility_ipa` is invoked and its stdout is redirected to the ipa.t.sol file with a little subsequent truncations of irrelevant lines. 

**Sidenote**

It is possible to vary number of variables and `test_solidity_compatibility_ipa` can produce correspondent IPA test-vector which is useful for detecting upper-bound gas cost experiments. 

P.S. As it is mentioned in https://github.com/lurk-lab/arecibo/issues/337, IPA now is a first building block that supports dynamic IO generation directly from Rust, and we can experiment with CI enforcements using it as an example in order to derive optimal compatibility rules for every stakeholder.
cc @samuelburnham

### CODE REVIEW

**Review by huitseeker — CHANGES_REQUESTED** [review]
Back to your queue for the file hierarchy changes requested in https://github.com/lurk-lab/arecibo/pull/341#pullrequestreview-1896652634

**Comment by storojs72** [comment]
> Back to your queue for the file hierarchy changes requested in [#341 (review)](https://github.com/lurk-lab/arecibo/pull/341#pullrequestreview-1896652634)

In this case, we will need to make even more fields public (`ck_v`, `ck_s` of `VerifierKey` and L_vec, `R_vec`, `a_hat` of `InnerProductArgument`) in order to access them from different module. Is that acceptable?

**Comment by huitseeker** [comment]
> In this case, we will need to make even more fields public (ck_v, ck_s of VerifierKey and L_vec, R_vec, a_hat of InnerProductArgument) in order to access them from different module. Is that acceptable?

Rust supports `pub (in crate::provider)`, which is fine, and `pub (crate)` if you must.

**Review by tchataigner — APPROVED** [review]
LGTM!

**Review by huitseeker — APPROVED** [review]
:pray:

**Review by samuelburnham — APPROVED** [review]

**Pull request merged**
